# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     container_name: Agile_Project
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       # Automatically run seed data on first startup
#       - ./seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql
#     ports:
#       - "${DB_PORT}:5432"
#     restart: unless-stopped

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: fetchaf-app
#     depends_on:
#       - db
#     environment:
#       - DB_USER=${DB_USER}
#       - DB_PASSWORD=${DB_PASSWORD}
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DB_NAME=${DB_NAME}
#       - COHERE_API_KEY=${COHERE_API_KEY}
#     ports:
#       - "8501:8501"
#     restart: unless-stopped

# volumes:
#   postgres_data: 

# version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fetchaf-app
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed_data.sql:/docker-entrypoint-initdb.d/seed_data.sql
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fetchaf-app
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - COHERE_API_KEY=${COHERE_API_KEY}
    ports:
      - "8501:8501"
    restart: unless-stopped

volumes:
  postgres_data:
